### ISSUE TITLE
dateOfBirth saknas i backend

### ISSUE THREAD

**Issue by Khaled85abo** [Marco30/Maverick#16]
Personnummret är inte obligatorisk därför ska vi ha en DateOfBirth i User model i backend.

**Comment by Evrid** [comment]
vill du att jag tar bort det personliga numret och lägger till en kolumn som heter DateOfBirth i backend?

**Comment by Evrid** [comment]
Solved with commit c37d87f7dd648d44c47b526bb00a092f1fa3b834, input format   
"dateOfBirth": "1959-08-24T11:49:26.760Z",
