### ISSUE TITLE
Ingen password hash

### ISSUE THREAD

**Issue by Khaled85abo** [Marco30/Maverick#17]
Lösenorde sparas som den är i backend.

**Comment by Evrid** [comment]
Solved in HashTest branch

**Comment by Evrid** [comment]
until commit 9c6fd75e8d77c3eba247fccb8f074a4c56ad82ef

**Comment by Evrid** [comment]
solved with commit 9c6fd75e8d77c3eba247fccb8f074a4c56ad82ef
