### ISSUE TITLE
Lösenordet skickas tillbaka med userInfo

### ISSUE THREAD

**Issue by Khaled85abo** [Marco30/Maverick#18]
När man anropper getUserInfo får man alla info om User till och med lösenordet.

**Comment by Evrid** [comment]
får du en token och ingen användarinformation alls? eller vill du ha vilken av nedanstående kvar?


    public int? Id { get; set; }
    public string? SocialSecurityNumber { get; set; }
    public string? FirstName { get; set; }
    public string? LastName { get; set; }
    public string? FullName { get; set; }
    public string? Email { get; set; }
    public string? Password { get; set; }

    [BindNever]   //use the DTO and have the Salt property without accepting it in the JSON input by ignore the Salt property during model binding.
    [JsonIgnore]  //let Swagger not show Salt
    public string? Salt { get; set; }
    public string? PhoneNumber { get; set; }
    public string? MobilePhoneNumber { get; set; }
    public bool AgreeMarketing { get; set; }
    public bool SubscribeToEmailNotification { get; set; }
    public string? ProfileImage { get; set; }

    public AddressDto? Address { get; set; }
    public string? Gender { get; set; }

**Comment by Khaled85abo** [comment]
Vi vill ha token och användarinformation, namnet till exempel är viktigt att visa i frontend, men vi vill inte skicka känsliga info till frontend. password ska inte skickas till frontend även om det är hashat.

**Comment by Evrid** [comment]
solved with commit 69172c5a0e79db197e409c8243bda1594719679c
