### ISSUE TITLE
Alltid 500 error status från backend

### ISSUE THREAD

**Issue by Khaled85abo** [Marco30/Maverick#19]
man vill skicka mer relevanta error till frontend. till exe: User försöker updatera lösenordet, men hen skickar ett fel gammalt lösenord. Då vill man skicka error status 400 till exe med tydligt beskrivning av problemet.

**Comment by Evrid** [comment]
Solved with commit 6dce98e9a056b9b2e9a8ab1831816e0a01d06040

**Comment by Evrid** [comment]
Solved with commit 6dce98e9a056b9b2e9a8ab1831816e0a01d06040

**Comment by PeterAlexander12** [comment]
Öppnar igen, för jag håller på att refaktorera alla Controllers och ser över felkoderna

**Comment by PeterAlexander12** [comment]
closed with 409409a7b1c881bf18399414cf6de044dd682784
