### ISSUE TITLE
User.DateOfBirth is null when registering a new user

### ISSUE THREAD

**Issue by PeterAlexander12** [Marco30/Maverick#22]
When registering using SocialSecurityNumber, we should extract the birthdate and save it to DateOfBirth

**Comment by Evrid** [comment]
solved with 3009eb8ebf5c72b9414ed4fd17b22dd581b45b4f

**Comment by Evrid** [comment]
solved with 3009eb8ebf5c72b9414ed4fd17b22dd581b45b4f
